name: Android CI

on:
  push:
    branches:
     - '*'
  pull_request:
    branches: 
     - 'main'

jobs:
#   unit_tests:
#     name: Run Unit Tests
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: Unit tests
#       run: ./gradlew test
      
#   android_tests:
#     runs-on: [ macos-latest ]
#     steps:
#       - uses: actions/checkout@v2

#       - name: Instrumentation Tests
#         uses: reactivecircus/android-emulator-runner@v2
#         with: 
#           api-level: 29
#           script: ./gradlew connectedAndroidTest

  apk:
      name: Generate Debug APK
      runs-on: ubuntu-18.04

      steps:
        - uses: actions/checkout@v1
        - name: set up JDK 11
          uses: actions/setup-java@v1
          with:
            java-version: 11
        - name: Make gradlew executable
          working-directory: ./SmartParkingApp
          run: chmod +x ./gradlew
        - name: Build with Gradle
          working-directory: ./SmartParkingApp
          run: ./gradlew build
        - name: Build debug APK
          working-directory: ./SmartParkingApp
          run: bash ./gradlew assembleDebug --stacktrace
        - name: Upload APK
          uses: actions/upload-artifact@v1
          with:
            name: Debug app
            path: ./SmartParkingApp/app/build/outputs/apk/debug/app-debug.apk
